---
version: ~> 1.0
language: python
python: "3.10"
dist: jammy

stages:
  - Quality
  - Publish


before_install:
  - pip install --upgrade pip
  - pip install poetry

install:
  - poetry install -v

jobs:
  include:
    - stage: Quality
      name: tests
      script:
        - python -m unittest
    - stage: Publish
      before_deploy:
        # API TOKEN environment variables is set
        # as hidden variables through
        # the web interface in the project settings.
        - poetry config repositories.testpypi http://test.pypi.org/legacy/
        - poetry config pypi-token.testpypi $MYPYPI_API_TOKEN
        - poetry build
      deploy:
        provider: script
        script:
          - echo Deploying to PyPI...
          - poetry publish -vvv --repository testpypi
          - echo Deployed.
        cleanup: false
        on:
          branch: main
          tags: true
      if: tag IS present